env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:import/recommended
  - google
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - import
  - '@typescript-eslint'
rules:
  '@typescript-eslint/explicit-function-return-type':
    - error
  import/first:
    - error
  import/newline-after-import:
    - error
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
      newlines-between: always
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
